application: pyeval
version: 2
runtime: python27
api_version: 1 

handlers:
- url: /static
  static_dir: static

- url: /worker
  script: pyeval.py
  login: admin

- url: /.*
  script: pyeval.py

libraries:
- name: webapp2
  version: latest
