application: pyeval
version: 2
runtime: python27
api_version: 1 
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /worker
  script: pyeval.app
  login: admin

- url: /.*
  script: pyeval.app

libraries:
- name: webapp2
  version: latest
