application: pyeval
version: 1
runtime: python27
api_version: 1 
threadsafe: false

handlers:

- url: /exec
  script: pyeval.py

- url: /get_id
  script: pyeval.py

- url: /worker
  script: pyeval.py
  login: admin

- url: /static
  static_dir: static

- url: /
  static_dir: static
